AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda function used as a tool in AI agent application on step functions.
Resources:
  StockAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tools.StockAnalyzerLambda::handleRequest
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      CodeUri: target/stock-analyzer-lambda-1.0-SNAPSHOT.jar