# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # {{cookiecutter.tool_description}}
  {{cookiecutter.tool_name}}:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/index.handler
      Description: "{{cookiecutter.tool_description}}"
      Runtime: nodejs18.x
      Timeout: 90
      MemorySize: 128
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: {{cookiecutter.tool_name}}
      Architectures:
        - arm64
      Policies:
        - SecretsManagerRead
        - AWSLambdaBasicExecutionRole