version = 0.1
[default.deploy.parameters]
stack_name = "extension-proxy-take-3"
resolve_s3 = true
s3_prefix = "extension-proxy-take-3"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
