# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LLMLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../../lambda_layer/python
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12 
  # Bedrock (Jamba) Lambda Function
  BedrockLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bedrock_lambda.lambda_handler
      Description: Bedrock (Jamba) Lambda
      Layers:
        - !Ref LLMLayer
      Runtime: python3.12
      Timeout: 90
      MemorySize: 128
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: ai-agent-llm
      Architectures:
        - arm64
      Policies:
        - AWSLambdaBasicExecutionRole        # Nova Lambda Function
  NovaLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: nova_lambda.lambda_handler
      Description: Nova Lambda
      Layers:
        - !Ref LLMLayer
      Runtime: python3.12
      Timeout: 90
      MemorySize: 128
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: ai-agent-llm
      Architectures:
        - arm64
      Policies:
        - AWSLambdaBasicExecutionRole      