[package]
name = "rust-clustering"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"

lambda_runtime = "0.13.0"
tokio = { version = "1", features = ["macros"] }
hdbscan = "0.9.0"
aws-config = "1.5.13"
serde = "1.0.217"
aws-sdk-s3 = "1.68.0"