[package]
name = "rust-clustering"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"

lambda_runtime = "0.13.0"
tokio = { version = "1", features = ["macros"] }
serde = "1.0.217"
anyhow = "1.0"

hdbscan = "0.9.0"
aws-config = "1.5.16"
aws-sdk-s3 = "1.76.0"
